# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-06 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0003_remove_project_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
