# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-07 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0005_remove_rating_creativity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='content_rating',
        ),
        migrations.RemoveField(
            model_name='project',
            name='design_rating',
        ),
        migrations.RemoveField(
            model_name='project',
            name='usability_rating',
        ),
        migrations.AddField(
            model_name='project',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='comment',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
